/*
 * This source file was generated by the Gradle 'init' task
 */
package com.osrs.toa

import com.osrs.toa.actors.GenericCombatEntity
import com.osrs.toa.actors.Player
import com.osrs.toa.sims.Akkha
import com.osrs.toa.weapons.Weapons

// Core tick-based system
data class Tick(val value: Int) {
    operator fun plus(other: Tick): Tick = Tick(value + other.value)
    operator fun minus(other: Tick): Tick = Tick(value - other.value)
    operator fun compareTo(other: Tick): Int = value.compareTo(other.value)
}

fun main() {
    var totalLength = 0;
    for (i in 1..1000) {
        val player = Player(
                GenericCombatEntity(
                        health = Health(99),
                        name = "Player",
                        hasLightbearer = false
                ),
                Weapons.MagussShadow,
                Weapons.ZaryteCrossbow
        )
        val monster = Akkha(player)
        val simulator = CombatSimulator(player, monster)
        val fightLength = simulator.runSimulation()
        // Print final status
        println("\nFinal Status:")
        println("fight lasted ${fightLength.value} ticks")
        totalLength += fightLength.value
    }
    val avgLength = totalLength/1000
    println("Average fight length over 1k iterations: $avgLength")

}
