/*
 * This source file was generated by the Gradle 'init' task
 */
package com.osrs.toa

import org.junit.jupiter.api.Test

class AppTest {
    
    @Test
    fun testCombatSimulatorCreation() {
        main()
    }
}
